version: '3'
services:
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

  app:
    build: .
    ports:
      - 3000:3000
    links:
      - redis
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://cache
    command:
      sh -c 'npm i && npm start'
