version: '3'
services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    expose:
      - 6379
    restart:
      always

  app:
    image: node:16-alpine
    volumes:
      - .:/usr/src/service
    working_dir: /usr/src/service
    command: bash -c "npm install && npm start"
    ports:
      - 3000:3000
    expose:
      - 3000
      - 6060
      - 80
